const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTOIMPAR = 'INCREMENTOIMPAR';
const INCREMENTOAZYNC = 'INCREMENTOAZYNC';

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTOIMPAR,
  INCREMENTOAZYNC
}